#!/bin/sh

set -e

case "$1" in
    upgrade)
        if /bin/pidof sirikali ; then
            echo "********************************************"
            echo "Sirikali must not be running when upgrading!"
            echo "********************************************"
	    exit 1
        fi
    ;;

    install|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument - $1" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
